permalink: pretty

collections:
  portfolio:
    output: true
  tools:
    output: true
  blog:
    output: true

defaults:
  -
    scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
      category: portfolio
  -
    scope:
      path: ""
      type: tools
    values:
      layout: post
      category: tools
  -
    scope:
      path: ""
      type: blog
    values:
      layout: post
      category: blog

# Setup
name:                 Matthias Pichler
title:                Matthias Pichler
tagline:              3D Artist and nerd dude man
description:          Portfolio and blog.<br> Python, 3D Animation & VFX and various other topics.

portfolioPerPage: 10

articlePerPage: 5
excerptTag: <!--more-->

url: http://www.matthiaspichler.com
add-url: 